#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DatabaseHelpDesk")]
	public partial class DataClassCategoriasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Categoria(tbl_Categoria instance);
    partial void Updatetbl_Categoria(tbl_Categoria instance);
    partial void Deletetbl_Categoria(tbl_Categoria instance);
    #endregion
		
		public DataClassCategoriasDataContext() : 
				base(global::HelpDesk.Properties.Settings.Default.DatabaseHelpDeskConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassCategoriasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassCategoriasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassCategoriasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassCategoriasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Categoria> tbl_Categorias
		{
			get
			{
				return this.GetTable<tbl_Categoria>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Categoria")]
	public partial class tbl_Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Cat;
		
		private string _Descricao_Cat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CatChanging(int value);
    partial void OnId_CatChanged();
    partial void OnDescricao_CatChanging(string value);
    partial void OnDescricao_CatChanged();
    #endregion
		
		public tbl_Categoria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Cat", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Cat
		{
			get
			{
				return this._Id_Cat;
			}
			set
			{
				if ((this._Id_Cat != value))
				{
					this.OnId_CatChanging(value);
					this.SendPropertyChanging();
					this._Id_Cat = value;
					this.SendPropertyChanged("Id_Cat");
					this.OnId_CatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao_Cat", DbType="VarChar(50)")]
		public string Descricao_Cat
		{
			get
			{
				return this._Descricao_Cat;
			}
			set
			{
				if ((this._Descricao_Cat != value))
				{
					this.OnDescricao_CatChanging(value);
					this.SendPropertyChanging();
					this._Descricao_Cat = value;
					this.SendPropertyChanged("Descricao_Cat");
					this.OnDescricao_CatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
