#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DatabaseHelpDesk")]
	public partial class DataClassOcorrenciaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Ocorrencia(tbl_Ocorrencia instance);
    partial void Updatetbl_Ocorrencia(tbl_Ocorrencia instance);
    partial void Deletetbl_Ocorrencia(tbl_Ocorrencia instance);
    #endregion
		
		public DataClassOcorrenciaDataContext() : 
				base(global::HelpDesk.Properties.Settings.Default.DatabaseHelpDeskConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassOcorrenciaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassOcorrenciaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassOcorrenciaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassOcorrenciaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Ocorrencia> tbl_Ocorrencias
		{
			get
			{
				return this.GetTable<tbl_Ocorrencia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Ocorrencia")]
	public partial class tbl_Ocorrencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Ocr;
		
		private string _Sol_Ocr;
		
		private System.Nullable<System.DateTime> _Data_Ocr;
		
		private string _Cat_Ocr;
		
		private string _Local_Ocr;
		
		private string _Equipamento_Ocr;
		
		private string _Descricao_Ocr;
		
		private string _Observacao_Ocr;
		
		private string _Tec_Ocr;
		
		private System.Nullable<System.DateTime> _DataSolucao_Ocr;
		
		private string _Solucao_Ocr;
		
		private string _Status_Ocr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_OcrChanging(int value);
    partial void OnId_OcrChanged();
    partial void OnSol_OcrChanging(string value);
    partial void OnSol_OcrChanged();
    partial void OnData_OcrChanging(System.Nullable<System.DateTime> value);
    partial void OnData_OcrChanged();
    partial void OnCat_OcrChanging(string value);
    partial void OnCat_OcrChanged();
    partial void OnLocal_OcrChanging(string value);
    partial void OnLocal_OcrChanged();
    partial void OnEquipamento_OcrChanging(string value);
    partial void OnEquipamento_OcrChanged();
    partial void OnDescricao_OcrChanging(string value);
    partial void OnDescricao_OcrChanged();
    partial void OnObservacao_OcrChanging(string value);
    partial void OnObservacao_OcrChanged();
    partial void OnTec_OcrChanging(string value);
    partial void OnTec_OcrChanged();
    partial void OnDataSolucao_OcrChanging(System.Nullable<System.DateTime> value);
    partial void OnDataSolucao_OcrChanged();
    partial void OnSolucao_OcrChanging(string value);
    partial void OnSolucao_OcrChanged();
    partial void OnStatus_OcrChanging(string value);
    partial void OnStatus_OcrChanged();
    #endregion
		
		public tbl_Ocorrencia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Ocr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Ocr
		{
			get
			{
				return this._Id_Ocr;
			}
			set
			{
				if ((this._Id_Ocr != value))
				{
					this.OnId_OcrChanging(value);
					this.SendPropertyChanging();
					this._Id_Ocr = value;
					this.SendPropertyChanged("Id_Ocr");
					this.OnId_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sol_Ocr", DbType="VarChar(50)")]
		public string Sol_Ocr
		{
			get
			{
				return this._Sol_Ocr;
			}
			set
			{
				if ((this._Sol_Ocr != value))
				{
					this.OnSol_OcrChanging(value);
					this.SendPropertyChanging();
					this._Sol_Ocr = value;
					this.SendPropertyChanged("Sol_Ocr");
					this.OnSol_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Ocr", DbType="Date")]
		public System.Nullable<System.DateTime> Data_Ocr
		{
			get
			{
				return this._Data_Ocr;
			}
			set
			{
				if ((this._Data_Ocr != value))
				{
					this.OnData_OcrChanging(value);
					this.SendPropertyChanging();
					this._Data_Ocr = value;
					this.SendPropertyChanged("Data_Ocr");
					this.OnData_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_Ocr", DbType="VarChar(50)")]
		public string Cat_Ocr
		{
			get
			{
				return this._Cat_Ocr;
			}
			set
			{
				if ((this._Cat_Ocr != value))
				{
					this.OnCat_OcrChanging(value);
					this.SendPropertyChanging();
					this._Cat_Ocr = value;
					this.SendPropertyChanged("Cat_Ocr");
					this.OnCat_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Local_Ocr", DbType="VarChar(50)")]
		public string Local_Ocr
		{
			get
			{
				return this._Local_Ocr;
			}
			set
			{
				if ((this._Local_Ocr != value))
				{
					this.OnLocal_OcrChanging(value);
					this.SendPropertyChanging();
					this._Local_Ocr = value;
					this.SendPropertyChanged("Local_Ocr");
					this.OnLocal_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipamento_Ocr", DbType="VarChar(50)")]
		public string Equipamento_Ocr
		{
			get
			{
				return this._Equipamento_Ocr;
			}
			set
			{
				if ((this._Equipamento_Ocr != value))
				{
					this.OnEquipamento_OcrChanging(value);
					this.SendPropertyChanging();
					this._Equipamento_Ocr = value;
					this.SendPropertyChanged("Equipamento_Ocr");
					this.OnEquipamento_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao_Ocr", DbType="VarChar(50)")]
		public string Descricao_Ocr
		{
			get
			{
				return this._Descricao_Ocr;
			}
			set
			{
				if ((this._Descricao_Ocr != value))
				{
					this.OnDescricao_OcrChanging(value);
					this.SendPropertyChanging();
					this._Descricao_Ocr = value;
					this.SendPropertyChanged("Descricao_Ocr");
					this.OnDescricao_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacao_Ocr", DbType="VarChar(50)")]
		public string Observacao_Ocr
		{
			get
			{
				return this._Observacao_Ocr;
			}
			set
			{
				if ((this._Observacao_Ocr != value))
				{
					this.OnObservacao_OcrChanging(value);
					this.SendPropertyChanging();
					this._Observacao_Ocr = value;
					this.SendPropertyChanged("Observacao_Ocr");
					this.OnObservacao_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tec_Ocr", DbType="VarChar(50)")]
		public string Tec_Ocr
		{
			get
			{
				return this._Tec_Ocr;
			}
			set
			{
				if ((this._Tec_Ocr != value))
				{
					this.OnTec_OcrChanging(value);
					this.SendPropertyChanging();
					this._Tec_Ocr = value;
					this.SendPropertyChanged("Tec_Ocr");
					this.OnTec_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSolucao_Ocr", DbType="Date")]
		public System.Nullable<System.DateTime> DataSolucao_Ocr
		{
			get
			{
				return this._DataSolucao_Ocr;
			}
			set
			{
				if ((this._DataSolucao_Ocr != value))
				{
					this.OnDataSolucao_OcrChanging(value);
					this.SendPropertyChanging();
					this._DataSolucao_Ocr = value;
					this.SendPropertyChanged("DataSolucao_Ocr");
					this.OnDataSolucao_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solucao_Ocr", DbType="VarChar(50)")]
		public string Solucao_Ocr
		{
			get
			{
				return this._Solucao_Ocr;
			}
			set
			{
				if ((this._Solucao_Ocr != value))
				{
					this.OnSolucao_OcrChanging(value);
					this.SendPropertyChanging();
					this._Solucao_Ocr = value;
					this.SendPropertyChanged("Solucao_Ocr");
					this.OnSolucao_OcrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Ocr", DbType="VarChar(50)")]
		public string Status_Ocr
		{
			get
			{
				return this._Status_Ocr;
			}
			set
			{
				if ((this._Status_Ocr != value))
				{
					this.OnStatus_OcrChanging(value);
					this.SendPropertyChanging();
					this._Status_Ocr = value;
					this.SendPropertyChanged("Status_Ocr");
					this.OnStatus_OcrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
