<?xml version="1.0" encoding="utf-8"?><Database Name="DatabaseHelpDesk" Class="DataClassCategoriasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\DatabaseHelpDesk.mdf;Integrated Security=True" SettingsObjectName="HelpDesk.Properties.Settings" SettingsPropertyName="DatabaseHelpDeskConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Categoria" Member="tbl_Categorias">
    <Type Name="tbl_Categoria">
      <Column Name="Id_Cat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descricao_Cat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>