<?xml version="1.0" encoding="utf-8"?><Database Name="DatabaseHelpDesk" Class="DataClassUsuariosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\DatabaseHelpDesk.mdf;Integrated Security=True" SettingsObjectName="HelpDesk.Properties.Settings" SettingsPropertyName="DatabaseHelpDeskConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Usuario" Member="tbl_Usuarios">
    <Type Name="tbl_Usuario">
      <Column Name="Id_Us" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome_Us" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ativo_Us" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email_Us" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NvAcesso_Us" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Login_Us" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Senha_Us" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>