#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DatabaseHelpDesk")]
	public partial class DataClassUsuariosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Usuario(tbl_Usuario instance);
    partial void Updatetbl_Usuario(tbl_Usuario instance);
    partial void Deletetbl_Usuario(tbl_Usuario instance);
    #endregion
		
		public DataClassUsuariosDataContext() : 
				base(global::HelpDesk.Properties.Settings.Default.DatabaseHelpDeskConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassUsuariosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassUsuariosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassUsuariosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassUsuariosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Usuario> tbl_Usuarios
		{
			get
			{
				return this.GetTable<tbl_Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Usuario")]
	public partial class tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Us;
		
		private string _Nome_Us;
		
		private System.Nullable<bool> _Ativo_Us;
		
		private string _Email_Us;
		
		private string _NvAcesso_Us;
		
		private string _Login_Us;
		
		private string _Senha_Us;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_UsChanging(int value);
    partial void OnId_UsChanged();
    partial void OnNome_UsChanging(string value);
    partial void OnNome_UsChanged();
    partial void OnAtivo_UsChanging(System.Nullable<bool> value);
    partial void OnAtivo_UsChanged();
    partial void OnEmail_UsChanging(string value);
    partial void OnEmail_UsChanged();
    partial void OnNvAcesso_UsChanging(string value);
    partial void OnNvAcesso_UsChanged();
    partial void OnLogin_UsChanging(string value);
    partial void OnLogin_UsChanged();
    partial void OnSenha_UsChanging(string value);
    partial void OnSenha_UsChanged();
    #endregion
		
		public tbl_Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Us", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Us
		{
			get
			{
				return this._Id_Us;
			}
			set
			{
				if ((this._Id_Us != value))
				{
					this.OnId_UsChanging(value);
					this.SendPropertyChanging();
					this._Id_Us = value;
					this.SendPropertyChanged("Id_Us");
					this.OnId_UsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_Us", DbType="VarChar(50)")]
		public string Nome_Us
		{
			get
			{
				return this._Nome_Us;
			}
			set
			{
				if ((this._Nome_Us != value))
				{
					this.OnNome_UsChanging(value);
					this.SendPropertyChanging();
					this._Nome_Us = value;
					this.SendPropertyChanged("Nome_Us");
					this.OnNome_UsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo_Us", DbType="Bit")]
		public System.Nullable<bool> Ativo_Us
		{
			get
			{
				return this._Ativo_Us;
			}
			set
			{
				if ((this._Ativo_Us != value))
				{
					this.OnAtivo_UsChanging(value);
					this.SendPropertyChanging();
					this._Ativo_Us = value;
					this.SendPropertyChanged("Ativo_Us");
					this.OnAtivo_UsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Us", DbType="VarChar(50)")]
		public string Email_Us
		{
			get
			{
				return this._Email_Us;
			}
			set
			{
				if ((this._Email_Us != value))
				{
					this.OnEmail_UsChanging(value);
					this.SendPropertyChanging();
					this._Email_Us = value;
					this.SendPropertyChanged("Email_Us");
					this.OnEmail_UsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NvAcesso_Us", DbType="VarChar(50)")]
		public string NvAcesso_Us
		{
			get
			{
				return this._NvAcesso_Us;
			}
			set
			{
				if ((this._NvAcesso_Us != value))
				{
					this.OnNvAcesso_UsChanging(value);
					this.SendPropertyChanging();
					this._NvAcesso_Us = value;
					this.SendPropertyChanged("NvAcesso_Us");
					this.OnNvAcesso_UsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login_Us", DbType="VarChar(50)")]
		public string Login_Us
		{
			get
			{
				return this._Login_Us;
			}
			set
			{
				if ((this._Login_Us != value))
				{
					this.OnLogin_UsChanging(value);
					this.SendPropertyChanging();
					this._Login_Us = value;
					this.SendPropertyChanged("Login_Us");
					this.OnLogin_UsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha_Us", DbType="VarChar(50)")]
		public string Senha_Us
		{
			get
			{
				return this._Senha_Us;
			}
			set
			{
				if ((this._Senha_Us != value))
				{
					this.OnSenha_UsChanging(value);
					this.SendPropertyChanging();
					this._Senha_Us = value;
					this.SendPropertyChanged("Senha_Us");
					this.OnSenha_UsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
