#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DatabaseHelpDesk")]
	public partial class DataClassesLocaisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Local(tbl_Local instance);
    partial void Updatetbl_Local(tbl_Local instance);
    partial void Deletetbl_Local(tbl_Local instance);
    #endregion
		
		public DataClassesLocaisDataContext() : 
				base(global::HelpDesk.Properties.Settings.Default.DatabaseHelpDeskConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLocaisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLocaisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLocaisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesLocaisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Local> tbl_Locals
		{
			get
			{
				return this.GetTable<tbl_Local>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Local")]
	public partial class tbl_Local : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Loc;
		
		private string _Desc_Loc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_LocChanging(int value);
    partial void OnId_LocChanged();
    partial void OnDesc_LocChanging(string value);
    partial void OnDesc_LocChanged();
    #endregion
		
		public tbl_Local()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Loc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Loc
		{
			get
			{
				return this._Id_Loc;
			}
			set
			{
				if ((this._Id_Loc != value))
				{
					this.OnId_LocChanging(value);
					this.SendPropertyChanging();
					this._Id_Loc = value;
					this.SendPropertyChanged("Id_Loc");
					this.OnId_LocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desc_Loc", DbType="VarChar(50)")]
		public string Desc_Loc
		{
			get
			{
				return this._Desc_Loc;
			}
			set
			{
				if ((this._Desc_Loc != value))
				{
					this.OnDesc_LocChanging(value);
					this.SendPropertyChanging();
					this._Desc_Loc = value;
					this.SendPropertyChanged("Desc_Loc");
					this.OnDesc_LocChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
